kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "fluentd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fluentd.name" . }}
    helm.sh/chart: {{ include "fluentd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
data:
{{- range $key, $value := .Values.configMaps }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- if .Values.metrics.enabled }}
  metrics.conf: |
    <source>
      @type prometheus
      port {{ .Values.metrics.service.port }}
    </source>

    <source>
      @type prometheus_monitor
    </source>

    <source>
      @type prometheus_output_monitor
    </source>
{{- end }}