apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluentd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fluentd.name" . }}
    helm.sh/chart: {{ include "fluentd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $port := .Values.service.ports }}
    - name: {{ $port.name }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol }}
      port: {{ $port.containerPort }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "fluentd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
