apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stackdriver-k8s-metrics.fullname" . }}-nanny-config
data:
  NannyConfiguration: |-
    apiVersion: nannyconfig/v1alpha1
    kind: NannyConfiguration
