# Service account for Heapster.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stackdriver-k8s-metrics.fullname" . }}

---
# ClusterRole with permissions required by Heapster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackdriver-user:{{ include "stackdriver-k8s-metrics.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - nodes
  - nodes/stats
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch

---
# ClusterRoleBinding for Heapster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackdriver-user:{{ include "stackdriver-k8s-metrics.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stackdriver-user:{{ include "stackdriver-k8s-metrics.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "stackdriver-k8s-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
