{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "service.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
