{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "service.fullname" . }}-pdb
spec:
  selector:
    matchLabels:
{{ include "service.fullname" . | indent 6 }}
{{ .Values.podDisruptionBudget | indent 2 }}
{{- end -}}