{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "service.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ template "service.fullname" . }}
{{ .Values.podDisruptionBudget | indent 2 }}
{{- end -}}