apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basic.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "basic.name" . }}
    helm.sh/chart: {{ include "basic.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "basic.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "basic.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "basic.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerPort }}
          ports:
            - name: http
              containerPort: {{ . }}
              protocol: TCP
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- range $name, $value := . }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if or (.Values.envFromSecrets) (.Values.envFromConfigMaps) }}
          envFrom:
            {{- range .Values.envFromConfigMaps }}
            - configMapRef:
                name: {{ . | quote }}
            {{- end }}
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.containerCommand }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.httpProbePath }}
          readinessProbe:
            httpGet:
              path: {{ . }}
              port: http
          {{- end }}
          {{- if .Values.secretMounts }}
          volumeMounts:
            {{- range $index, $secretMount := .Values.secretMounts }}
            - name: secret-volume-{{ $index }}
              mountPath: {{ $secretMount.mountPath }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | trim | nindent 8}}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.secretMounts }}
      volumes:
        {{- range $index, $secretMount := .Values.secretMounts }}
        - name: secret-volume-{{ $index }}
          secret:
            secretName: {{ $secretMount.secretName }}
        {{- end }}
      {{- end }}
